// PLACEHOLDER CONTENT — único punto de verdad del menú de infusiones.
// Precios en CLP, ficticios pero realistas para el mercado chileno.
// Reemplazar por la carta real, precios y fotografía de Apolo Coffee antes
// de lanzar el sitio a producción.

import type { MenuItem, MenuCategory } from "@/types/menu";

export const menuCategories: { id: MenuCategory; label: string }[] = [
  { id: "espresso", label: "Espresso" },
  { id: "filtrado", label: "Filtrado" },
  { id: "especiales", label: "Especiales" },
  { id: "frio", label: "Frío" },
];

export const menuItems: MenuItem[] = [
  {
    id: "espresso-apolo",
    name: "Espresso Apolo",
    description: "Doble shot de nuestra mezcla de la casa, cuerpo denso y notas a cacao.",
    price: 2200,
    category: "espresso",
    roastLevel: "dark",
  },
  {
    id: "cortado-roasted-tan",
    name: "Cortado",
    description: "Espresso cortado con un toque de leche vaporizada, textura sedosa.",
    price: 2500,
    category: "espresso",
    roastLevel: "dark",
  },
  {
    id: "ristretto-doble",
    name: "Ristretto Doble",
    description: "Extracción corta y concentrada, dulzor intenso y crema espesa.",
    price: 2300,
    category: "espresso",
    roastLevel: "dark",
  },
  {
    id: "macchiato-clasico",
    name: "Macchiato Clásico",
    description: "Espresso manchado con una nube de leche, textura sedosa y equilibrio.",
    price: 2400,
    category: "espresso",
    roastLevel: "dark",
  },
  {
    id: "americano-apolo",
    name: "Americano Apolo",
    description: "Espresso alargado con agua caliente, cuerpo suave y aromático.",
    price: 2300,
    category: "espresso",
    roastLevel: "dark",
  },
  {
    id: "v60-finca-esperanza",
    name: "V60 Finca La Esperanza",
    description: "Perfil floral y cítrico, tueste claro de altura, ideal para paladares curiosos.",
    price: 3200,
    category: "filtrado",
    roastLevel: "light",
    tags: ["temporada"],
  },
  {
    id: "chemex-sur",
    name: "Chemex del Sur",
    description: "Taza limpia y balanceada, notas a caramelo y frutos secos.",
    price: 3400,
    category: "filtrado",
    roastLevel: "medium",
  },
  {
    id: "aeropress-honduras",
    name: "AeroPress Honduras",
    description: "Taza limpia y dulce, notas a panela y frutos rojos.",
    price: 3300,
    category: "filtrado",
    roastLevel: "light",
  },
  {
    id: "kalita-wave-etiopia",
    name: "Kalita Wave Etiopía",
    description: "Perfil té-like, jazmín y bergamota, cuerpo ligero.",
    price: 3400,
    category: "filtrado",
    roastLevel: "light",
    tags: ["temporada"],
  },
  {
    id: "prensa-francesa",
    name: "Prensa Francesa",
    description: "Cuerpo pesado y textura untuosa, ideal para paladares intensos.",
    price: 3100,
    category: "filtrado",
    roastLevel: "medium",
  },
  {
    id: "latte-avellanas",
    name: "Latte de Avellanas",
    description: "Espresso, leche vaporizada y jarabe artesanal de avellanas tostadas.",
    price: 3800,
    category: "especiales",
    roastLevel: "medium",
    tags: ["nuevo"],
  },
  {
    id: "flat-white-apolo",
    name: "Flat White Apolo",
    description: "Microespuma aterciopelada sobre un doble ristretto, equilibrio perfecto.",
    price: 3500,
    category: "especiales",
    roastLevel: "medium",
  },
  {
    id: "mocaccino-apolo",
    name: "Mocaccino Apolo",
    description: "Espresso, chocolate al 70% y leche vaporizada, dulzura equilibrada.",
    price: 3700,
    category: "especiales",
    roastLevel: "medium",
  },
  {
    id: "capuccino-canela",
    name: "Capuccino de Canela",
    description: "Espuma densa espolvoreada con canela de Ceilán.",
    price: 3400,
    category: "especiales",
    roastLevel: "medium",
  },
  {
    id: "chai-latte-apolo",
    name: "Chai Latte Apolo",
    description: "Especias de autor infusionadas en leche vaporizada, sin café.",
    price: 3600,
    category: "especiales",
    roastLevel: "medium",
    tags: ["nuevo"],
  },
  {
    id: "cold-brew-12h",
    name: "Cold Brew 12h",
    description: "Extracción en frío por 12 horas, dulzura natural y baja acidez.",
    price: 3600,
    category: "frio",
    roastLevel: "dark",
    tags: ["temporada"],
  },
  {
    id: "iced-latte-coco",
    name: "Iced Latte de Coco",
    description: "Espresso, leche de coco y hielo — fresco, cremoso y sin lactosa.",
    price: 3900,
    category: "frio",
    roastLevel: "light",
    tags: ["nuevo"],
  },
  {
    id: "nitro-cold-brew",
    name: "Nitro Cold Brew",
    description: "Infusión en frío con nitrógeno, textura cremosa y sin lácteos.",
    price: 3900,
    category: "frio",
    roastLevel: "dark",
  },
  {
    id: "affogato-apolo",
    name: "Affogato Apolo",
    description: "Bocha de helado de vainilla bañada en un doble espresso.",
    price: 3800,
    category: "frio",
    roastLevel: "dark",
  },
  {
    id: "iced-matcha-latte",
    name: "Iced Matcha Latte",
    description: "Matcha ceremonial con leche fría, dulzura sutil, sin café.",
    price: 3700,
    category: "frio",
    roastLevel: "light",
    tags: ["nuevo"],
  },
];
